2020-11-17 11:12:31,270 DEBUG    root            Loaded Command Group: ['gcloud', 'compute']
2020-11-17 11:12:31,274 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'regions']
2020-11-17 11:12:31,287 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'regions', 'list']
2020-11-17 11:12:31,290 DEBUG    root            Running [gcloud.compute.regions.list] with arguments: []
2020-11-17 11:12:31,395 INFO     root            Display format: "        table(
          name,
          quotas.metric.CPUS.quota():label=CPUS,
          quotas.metric.DISKS_TOTAL_GB.quota():label=DISKS_GB,
          quotas.metric.IN_USE_ADDRESSES.quota():label=ADDRESSES,
          quotas.metric.STATIC_ADDRESSES.quota():label=RESERVED_ADDRESSES,
          status():label=STATUS,
          deprecated.deleted:label=TURNDOWN_DATE
        )"
2020-11-17 11:12:52,077 DEBUG    root            (gcloud.compute.regions.list) Some requests did not succeed:
 - Project 145157111548 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=145157111548 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Traceback (most recent call last):
  File "/Users/bobbysmith/Downloads/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 983, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/bobbysmith/Downloads/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = display.Displayer(command_instance, args, resources,
  File "/Users/bobbysmith/Downloads/google-cloud-sdk/lib/googlecloudsdk/calliope/display.py", line 483, in Display
    self._printer.Print(self._resources)
  File "/Users/bobbysmith/Downloads/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_printer_base.py", line 275, in Print
    for resource in resources:
  File "/Users/bobbysmith/Downloads/google-cloud-sdk/lib/googlecloudsdk/core/util/peek_iterable.py", line 211, in __next__
    item = self._NextItem()
  File "/Users/bobbysmith/Downloads/google-cloud-sdk/lib/googlecloudsdk/core/util/peek_iterable.py", line 183, in _NextItem
    return next(self._iterable)
  File "/Users/bobbysmith/Downloads/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/lister.py", line 922, in __call__
    utils.RaiseException(errors, ListException)
  File "/Users/bobbysmith/Downloads/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 133, in RaiseException
    raise exception(
googlecloudsdk.api_lib.compute.lister.ListException: Some requests did not succeed:
 - Project 145157111548 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=145157111548 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

2020-11-17 11:12:52,088 ERROR    root            (gcloud.compute.regions.list) Some requests did not succeed:
 - Project 145157111548 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=145157111548 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

